### ISSUE TITLE
missing product.sys, cmdline or product.txt

### ISSUE THREAD

**Issue by rodrigomr** [DrJWCain/VFS#2]
Hello, I saw the presentation at SDC conference and I am messing around a little, trying to run some tests.

Following the steps in the README, when running _KernelServer.exe_ I am getting the error:

> Required information "developer" not found - expected in product.sys, cmdline or product.txt.

Taking a quick look at the code I've seen that other information are retrieved from those files, such as _product_ , _version_, _settings_...

Did I miss something or are those files really missing?

Thanks in advance.

**Comment by DrJWCain** [comment]
Hi,

Thanks for your emails, I’m in the Uk time zone, so I’ll get back to you tomorrow morning (so overnight your time?) if that’s OK? 

Cheers,

James.

**Comment by rodrigomr** [comment]
That's no problem at all.

Thanks in advance.

Em ter, 2 de out de 2018 15:46, Dr James Westland Cain <
notifications@github.com> escreveu:

> Hi,
>
> Thanks for your emails, I’m in the Uk time zone, so I’ll get back to you
> tomorrow morning (so overnight your time?) if that’s OK?
>
> Cheers,
>
> James.
>
> Sent from my iPhone
>

**Comment by DrJWCain** [comment]
Hi Rodrigo,

Thanks for the feedback!

I have reviewed this issue, and yes - you have found missing files, that I
had locally, but were not checked in - thank you!
I have pushed the missing files so all should be working now. I've done
this by editing the .gitignore - as the bug was in there.

I would advise you get the software to re-install (as some of the missing
files were default registry settings).
You can provoke this by deleting the registry the Kernel makes
at: HKEY_LOCAL_MACHINE\SOFTWARE\vfs\SMB3 Server.
(In your case this might not have been made yet, as the product.txt file
missing breaks the boot very early).
In either case, then run kernelserver.exe with elevated privileges. It will
ask for elevation if it hasn't got permissions and needs them.

Let me know how you get on.

Cheers,

James.

P.s. I have also accepted the changes in your pull request - than you very
much! Interesting that VS2015 was OK, but VS2017 was not?

**Comment by DrJWCain** [comment]
I think this issue should now be closed. Awaiting confirmation from @rodrigomr .

**Comment by rodrigomr** [comment]
Thanks a lot for the quick reply James.  Now I managed to run the KernelServer.

This is the summary I am getting:

> 08:17:04.510  4420     -KERNELEXEC DLL
08:17:04.510  4420      {
08:17:04.510  4420       -KERNELEXEC Intialised modules
08:17:04.510  4420        {
08:17:04.510  4420          KERNELEXEC Current KernelSDK version is 5.3.1.0
08:17:04.510  4420          KERNELEXEC
08:17:04.510  4420          KERNELEXEC Load  Developer  Module                           Module     Base              Modified             Status
08:17:04.510  4420          KERNELEXEC Order                                             Version    Address           Date & Time
08:17:04.510  4420          KERNELEXEC
08:17:04.510  4420          KERNELEXEC 0     vfs        _KernelExec                      9.1.0.0    0000000180000000  03/10/2018 12:47:33  CU Ignored, Reg written, Reg written, Installed (First time install, ), Init
08:17:04.510  4420          KERNELEXEC 50    vfs        KernelDebugDriver                1.1.0.0    000000006FD10000  03/10/2018 12:48:00  CU Ignored, Reg written, Reg written, Installed (First time install, ), Init
08:17:04.510  4420          KERNELEXEC 101   vfs        KernelFileLogDriver              2.2.0.0    00000000008D0000  03/10/2018 12:47:50  CU Ignored, Reg written, Reg written, Installed (First time install, ), Init
08:17:04.510  4420          KERNELEXEC 199   vfs        KernelConsoleLogDriver           1.13.0.0   000000006FD40000  03/10/2018 12:48:01  CU Ignored, Reg written, Reg written, Installed (First time install, ), Init
08:17:04.510  4420          KERNELEXEC 1300  vfs        QCIFSCommon                      0.1.0.0    00007FFA7E260000  03/10/2018 12:47:49  CU Ignored, Installed (First time install, ), Init
08:17:04.510  4420          KERNELEXEC 1400  vfs        QCIFSFwk                         0.0.1.0    0000000000000000  03/10/2018 12:48:00  CU Ignored, Ignore because LoadLibrary failed (Tried to LoadLibraryEx() on "C:\Users\VPN-USER\Documents\VFS\data\x64\DLL_Code_Release\vfs_QCIFSFwk.dll" - returned 126 (0x7e, The specified module could not be found. ))
08:17:04.510  4420          KERNELEXEC 1400  vfs        QCIFSProcessor                   1.2.1.0    00007FFA6B930000  03/10/2018 12:47:51  CU Ignored, Installed (First time install, ), Init failed (Tried to RegOpenKeyEx() at "Software\Vfs\SMB3 Server\vfs\QCIFSProcessor\1.2.1.x\Custom Settings\Config" (item "SMB credits") - returned "The system cannot find the file specified. ")
08:17:04.510  4420          KERNELEXEC 1400  vfs        SocketServer                     1.0.1.0    00007FFA7E220000  03/10/2018 12:47:50  CU Ignored, Installed (First time install, ), Init
08:17:04.510  4420          KERNELEXEC 1500  vfs        QCIFSIPC                         0.0.1.0    0000000000000000  03/10/2018 12:48:00  CU Ignored, Ignore because LoadLibrary failed (Tried to LoadLibraryEx() on "C:\Users\VPN-USER\Documents\VFS\data\x64\DLL_Code_Release\vfs_QCIFSIPC.dll" - returned 126 (0x7e, The specified module could not be found. ))
08:17:04.510  4420          KERNELEXEC 1700  vfs        QCIFSSofa                        0.0.1.0    0000000000000000  03/10/2018 12:48:07  CU Ignored, Ignore because LoadLibrary failed (Tried to LoadLibraryEx() on "C:\Users\VPN-USER\Documents\VFS\data\x64\DLL_Code_Release\vfs_QCIFSSofa.dll" - returned 126 (0x7e, The specified module could not be found. ))
08:17:04.510  4420          KERNELEXEC 1700  vfs        QCIFSTest                        0.0.1.0    00007FFA7B590000  03/10/2018 12:47:51  CU Ignored, Installed (First time install, ), Init
08:17:04.510  4420        }
08:17:04.510  4420      }
08:17:04.510  4420     +KERNELEXEC DLL Detail...
08:17:04.510  4420     -KERNELEXEC Factory
08:17:04.510  4420      {
08:17:04.510  4420        KERNELEXEC 24 classes registered
08:17:04.510  4420        KERNELEXEC 17 instances created
08:17:04.510  4420      }
08:17:04.510  4420     +KERNELEXEC Factory Detail...
08:17:04.558  5728   +LOG Started thread...
08:17:05.265  1164   +ONE SECOND TIMER Starting timer...
08:17:06.522  4420    }
08:17:06.522  4420   -KERNELEXEC Stopped thread

I noticed that the QCIFSProcessor startup failed. Also some other modules such as QCIFSFwk were ignored. Is this OK?

Taking a look at the log, I haven't seen the VFS_SOCKETSERVER there, therefore I can't find anything related with the bind of 445 port. I guess I might have done something wrong.

Thanks again for your time.

P.S. I have not tested with VS2015 :(. Were it building normally?

**Comment by DrJWCain** [comment]
Hi,

Fascinating! No that’s not correct. I built and ran with latest VS 2017 today - upgrading to v141 in the process. All 14 binaries are required to be running. 

Do you have a folder called C:\data\logs? If not, could you make this folder and run up again? There should be html log files in there. Could you post the most recent?

Also, just checking you have the boost dlls on your path? They need to be found by at least 4 of the plugins. 

Cheers,

James.

**Comment by rodrigomr** [comment]
I do have the logs, follow the one right after removing HKEY_LOCAL_MACHINE\SOFTWARE\vfs\SMB3 Server and the other after the second startup.

[logs.zip](https://github.com/DrJWCain/VFS/files/2443254/logs.zip)

In fact I don't have the boost DLLs in my path, I will set it up and get back to you.

Thanks again mate.

**Comment by rodrigomr** [comment]
Very nice, these are the new logs after placing the boost dlls in my path:

[logs_2.zip](https://github.com/DrJWCain/VFS/files/2443411/logs_2.zip)

I guess the only one with problems is the QCIFSProcessor?

**Comment by DrJWCain** [comment]
Sorry - you've found another oversight when I created the initial git repo!
(I'm sure I tried a fresh checkout when I made the repo, I suspect I had a
pre-made set of registry settings that I had failed to delete - so I missed
this missing files).

I have pushed some changes to fix it. so, pull again, delete
HKEY_LOCAL_MACHINE\SOFTWARE\vfs\SMB3 Server. again and have another go!
Let me know how you get on again.

Cheers,

James.

**Comment by rodrigomr** [comment]
Hello James!

Sorry for the late reply, I have just managed to test it again now.
Now all the modules get to work, I've tried the `net use * \\127.0.0.1\test` and the share is working like a charm.

I was working if we could use the VFS to access local shares or drives, like C$...

Thanks again for all the help mate,

Rodrigo

**Comment by DrJWCain** [comment]
That’s great news - thanks Rodrigo. 

There’s no sample that re-maps the local disk - maybe a tutorial for students ;-)

I’ll think about starting a new ‘worked ‘ example as an extra plugin. 

Cheers again & thanks for the interest. 

Why not try getting the ‘sofa’ plugin working? I’ve written an extra readme.md in the QCIFSSofa folder to start you off. 

Cheers,

James.

**Comment by DrJWCain** [comment]
This issue is now closed - thanks for the feedback.
